import bcrypt from 'bcryptjs';
import { PrismaClient } from '@prisma/client';
import { defaultSolutions, defaultProjects, defaultCompanyInfo } from '../../src/data/defaultData.js';
const prisma=new PrismaClient();
const plans=[
  {name:'Starter POS',slug:'erp-starter',startingPrice:49000,suitableFor:'Small shops and single-counter businesses.',summary:'Reliable billing and essential stock control.',supportPeriod:'30 days free corrective support',features:['POS billing and checkout','Product and category management','Barcode and receipt printing','Customer management','Basic stock tracking','Daily and monthly sales reports','One branch and one POS counter']},
  {name:'Professional POS',slug:'erp-professional',startingPrice:90000,suitableFor:'Growing retail businesses.',summary:'Purchasing, costing, reporting, and multi-user operations.',supportPeriod:'3 months free corrective support',mostPopular:true,features:['Everything in Starter','Supplier and purchase management','Expense and outstanding tracking','Product costing and stock valuation','Advanced sales and profit reports','Multiple users and roles','Custom receipt and selected reports']},
  {name:'Enterprise POS',slug:'erp-enterprise',startingPrice:125000,suitableFor:'Multi-branch and medium-to-large businesses.',summary:'Advanced multi-branch control, accounting, workflows, and integrations.',supportPeriod:'3 months priority corrective support',licenceNote:'Odoo Enterprise licence charged separately where applicable.',features:['Everything in Professional','Multiple branches and warehouses','Branch stock transfers','Batch, serial and expiry tracking','Advanced accounting and approvals','Custom dashboards and workflows','API and third-party integrations']}
];
async function main(){
  if(!process.env.INITIAL_ADMIN_PASSWORD)throw new Error('Set INITIAL_ADMIN_PASSWORD before running the seed');
  await prisma.adminUser.upsert({where:{username:'ADMIN'},update:{},create:{username:'ADMIN',passwordHash:await bcrypt.hash(process.env.INITIAL_ADMIN_PASSWORD,12)}});
  await prisma.companyInfo.upsert({where:{id:'company'},update:{content:defaultCompanyInfo},create:{id:'company',name:defaultCompanyInfo.name||'InfoAxon Software Solutions',phone:defaultCompanyInfo.phone,whatsapp:'94711474064',email:defaultCompanyInfo.email,address:defaultCompanyInfo.address,socialLinks:defaultCompanyInfo.socialLinks,content:defaultCompanyInfo}});
  for(let i=0;i<defaultSolutions.length;i++){const s=defaultSolutions[i],slug=s.id||('solution-'+i);await prisma.solution.upsert({where:{slug},update:{title:s.title,description:s.description||s.shortDescription||s.title,content:s},create:{slug,title:s.title,subtitle:s.subtitle||s.tagline,description:s.description||s.shortDescription||s.title,icon:typeof s.icon==='string'?s.icon:null,imageUrl:s.image,content:s,displayOrder:i+1}});}
  for(let i=0;i<defaultProjects.length;i++){const p=defaultProjects[i],slug=p.id||('project-'+i);await prisma.project.upsert({where:{slug},update:{title:p.title,description:p.description||p.title,content:p},create:{slug,title:p.title,category:p.category,description:p.description||p.title,imageUrl:p.image,content:p,featured:Boolean(p.featured),displayOrder:i+1}});}
  for(let i=0;i<plans.length;i++){const {features,...data}=plans[i];const pkg=await prisma.softwarePackage.upsert({where:{slug:data.slug},update:data,create:{...data,displayOrder:i+1}});await prisma.packageFeature.deleteMany({where:{packageId:pkg.id}});await prisma.packageFeature.createMany({data:features.map((text,n)=>({packageId:pkg.id,text,featured:true,displayOrder:n+1}))});}
  const categories=['Touchscreen POS Terminal','Desktop PC / Mini PC','Barcode Scanner','Receipt Printer','Cash Drawer','Customer Display','Label Printer','Barcode Labels','UPS','Router','Weighing Scale','Keyboard and Mouse'];
  for(let i=0;i<categories.length;i++){const name=categories[i],slug=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');await prisma.productCategory.upsert({where:{slug},update:{},create:{name,slug,displayOrder:i+1}});}
  const products=[['15.6-inch Touch POS Terminal','touch-pos-terminal','Touchscreen POS Terminal',185000,'Intel processor, 8GB RAM and 128GB SSD.','computer'],['Business Mini PC','mini-pc','Desktop PC / Mini PC',95000,'8GB RAM, 256GB SSD, Wi-Fi and USB.','computer'],['2D USB Barcode Scanner','barcode-scanner','Barcode Scanner',14500,'Fast 1D/2D USB scanning.','scanner'],['80mm Thermal Receipt Printer','receipt-printer','Receipt Printer',28500,'High-speed USB and LAN printing.','receipt-printer'],['Heavy-duty Cash Drawer','cash-drawer','Cash Drawer',16500,'Secure five-note and eight-coin compartments.','cash-drawer'],['USB Customer Pole Display','customer-display','Customer Display',22000,'Dual-line adjustable customer display.','display'],['Desktop Barcode Label Printer','label-printer','Label Printer',42000,'Direct thermal product label printing.','label-printer'],['Thermal Barcode Label Roll','barcode-labels','Barcode Labels',1850,'Premium adhesive retail labels.','labels'],['1200VA Line-interactive UPS','ups','UPS',27500,'Power protection for POS equipment.','ups'],['Dual-band Business Router','router','Router',12500,'Reliable wired and wireless networking.','router'],['Retail Digital Weighing Scale','weighing-scale','Weighing Scale',32000,'Accurate retail weighing with dual display.','scale'],['Wired Keyboard and Mouse Combo','keyboard-mouse','Keyboard and Mouse',6500,'Durable USB input devices.','input']];
  for(let i=0;i<products.length;i++){const [name,slug,categoryName,price,shortDescription,compatibilityType]=products[i],category=await prisma.productCategory.findUnique({where:{slug:categoryName.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}});await prisma.product.upsert({where:{slug},update:{},create:{name,slug,categoryId:category.id,shortDescription,specifications:{compatibilityType},price,warranty:'1 year warranty',stockQuantity:10,stockStatus:'IN_STOCK',displayOrder:i+1}});}
  const rules=[['touchscreen-pos-terminal','REQUIRED','Add a POS terminal or computer.','Runs the POS software and peripherals.',true],['barcode-scanner','REQUIRED','Add a barcode scanner.','Provides fast and accurate checkout.',true],['receipt-printer','REQUIRED','Add a receipt printer.','Provides customer receipts.',true],['cash-drawer','RECOMMENDED','Consider adding a cash drawer.','Keeps cash secure and organised.',false],['ups','RECOMMENDED','Consider adding a UPS.','Protects equipment from power interruptions.',false]];
  for(let i=0;i<rules.length;i++){const [categorySlug,level,message,explanation,allowOwnedConfirmation]=rules[i],category=await prisma.productCategory.findUnique({where:{slug:categorySlug}}),suggested=await prisma.product.findFirst({where:{categoryId:category.id}});if(!(await prisma.compatibilityRule.findFirst({where:{categoryId:category.id}})))await prisma.compatibilityRule.create({data:{categoryId:category.id,suggestedProductId:suggested?.id,level,message,explanation,allowOwnedConfirmation,displayOrder:i+1}});}
  const erp=[['01','Smart POS Billing','Fast and accurate billing with barcode scanning, receipt printing, discounts, returns, and smooth checkout.','/images/solutions/erp-pos/smart-pos-billing.png'],['02','Inventory & Stock Control','Track stock quantities in real time, manage stock-in and stock-out, and monitor low-stock items easily.','/images/solutions/erp-pos/inventory-stock-control.png'],['03','Purchase & Supplier Management','Manage suppliers, purchase orders, goods receiving, and product costing in one connected system.','/images/solutions/erp-pos/purchase-supplier-management.png'],['04','Multi-branch Reports & Growth','Monitor branches, sales, stock, and performance with clear reports and business insights.','/images/solutions/erp-pos/multi-branch-reporting.png']];
  for(let i=0;i<erp.length;i++){const [number,title,description,imageUrl]=erp[i];if(!(await prisma.erpKeyFeature.findFirst({where:{number}})))await prisma.erpKeyFeature.create({data:{number,title,description,imageUrl,displayOrder:i+1}});}
}
main().finally(()=>prisma.$disconnect());
