import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {AnimatePresence,motion} from 'framer-motion';
import {HiArrowLeft,HiChevronLeft,HiChevronRight,HiExternalLink,HiX} from 'react-icons/hi';
import {useData} from '../context/DataContext';

export default function ProjectDetail(){const {id}=useParams(),{projects,loading}=useData(),project=projects.find(p=>p.id===id),[active,setActive]=useState(null);useEffect(()=>{const close=e=>e.key==='Escape'&&setActive(null);window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);if(loading)return <div className="grid min-h-screen place-items-center bg-white text-dark-500 dark:bg-dark-950">Loading project...</div>;if(!project)return <div className="grid min-h-screen place-items-center bg-white px-4 text-center dark:bg-dark-950"><div><h1 className="text-3xl font-bold text-dark-900 dark:text-white">Project not found</h1><Link to="/projects" className="btn-primary mt-6">Back to Projects</Link></div></div>;const images=Array.isArray(project.images)?project.images:[],technologies=Array.isArray(project.technologies)?project.technologies:[],results=Array.isArray(project.results)?project.results:[],cover=images[0]||project.imageUrl;const move=n=>setActive(i=>(i+n+images.length)%images.length);return <main className="min-h-screen bg-white dark:bg-dark-950">
 <section className="border-b border-dark-200 bg-dark-50 pt-28 dark:border-dark-800 dark:bg-dark-900/40"><div className="mx-auto max-w-7xl px-4 pb-14 sm:px-6 lg:px-8"><Link to="/projects" className="inline-flex items-center gap-2 text-sm font-semibold text-dark-500 hover:text-primary-600 dark:text-dark-400"><HiArrowLeft/>All projects</Link><div className="mt-9 grid items-end gap-10 lg:grid-cols-[1fr_auto]"><div className="max-w-4xl">{project.category&&<p className="mb-4 text-sm font-bold uppercase tracking-[.18em] text-primary-600 dark:text-primary-400">{project.category}</p>}<h1 className="text-4xl font-extrabold leading-tight text-dark-950 dark:text-white sm:text-5xl lg:text-6xl">{project.title}</h1>{project.client&&<p className="mt-5 text-lg text-dark-500 dark:text-dark-300">Created for <span className="font-semibold text-dark-800 dark:text-white">{project.client}</span></p>}</div>{project.demoUrl&&<a href={project.demoUrl} target={/^https?:\/\//i.test(project.demoUrl)?'_blank':undefined} rel="noopener noreferrer" className="btn-primary w-full justify-center sm:w-auto">View Live Project <HiExternalLink/></a>}</div></div></section>
 {cover&&<section className="mx-auto max-w-7xl px-4 pt-10 sm:px-6 lg:px-8"><button type="button" onClick={()=>setActive(0)} className="block w-full overflow-hidden rounded-2xl border border-dark-200 bg-dark-100 dark:border-dark-800 dark:bg-dark-900"><img src={cover} alt={`${project.title} cover`} className="aspect-[16/7] w-full object-cover"/></button></section>}
 <section className="mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[minmax(0,1fr)_320px] lg:px-8"><div className="min-w-0 space-y-16"><article><p className="text-xs font-bold uppercase tracking-[.18em] text-primary-600 dark:text-primary-400">Case study</p><h2 className="mt-3 text-3xl font-bold text-dark-900 dark:text-white">Project overview</h2><div className="mt-6 whitespace-pre-line text-base leading-8 text-dark-600 dark:text-dark-300 sm:text-lg">{project.description}</div></article>{results.length>0&&<section><h2 className="text-2xl font-bold text-dark-900 dark:text-white">Key outcomes</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{results.map((x,i)=><div key={i} className="flex gap-4 border-l-2 border-primary-500 bg-dark-50 p-5 dark:bg-dark-900"><span className="font-bold text-primary-600">{String(i+1).padStart(2,'0')}</span><p className="leading-6 text-dark-700 dark:text-dark-200">{x}</p></div>)}</div></section>}{images.length>1&&<section><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary-600 dark:text-primary-400">Gallery</p><h2 className="mt-2 text-3xl font-bold text-dark-900 dark:text-white">Project screens</h2></div><span className="text-sm text-dark-400">{images.length} images</span></div><div className="mt-7 grid gap-5 sm:grid-cols-2">{images.slice(1).map((img,i)=><button type="button" key={img} onClick={()=>setActive(i+1)} className="overflow-hidden rounded-xl border border-dark-200 bg-dark-100 dark:border-dark-800 dark:bg-dark-900"><img src={img} alt={`${project.title} screen ${i+2}`} className="aspect-video w-full object-cover transition-transform duration-300 hover:scale-[1.02]"/></button>)}</div></section>}</div>
 <aside><div className="space-y-8 border-t border-dark-200 pt-7 lg:sticky lg:top-28 dark:border-dark-800"><div><h3 className="text-xs font-bold uppercase tracking-[.16em] text-dark-400">Project details</h3><dl className="mt-5 divide-y divide-dark-200 text-sm dark:divide-dark-800">{project.client&&<Fact label="Client" value={project.client}/>} {project.category&&<Fact label="Category" value={project.category}/>}<Fact label="Gallery" value={`${images.length} image${images.length===1?'':'s'}`}/></dl></div>{technologies.length>0&&<div><h3 className="text-xs font-bold uppercase tracking-[.16em] text-dark-400">Technology</h3><div className="mt-4 flex flex-wrap gap-2">{technologies.map(x=><span key={x} className="rounded-md border border-dark-200 px-3 py-2 text-sm font-medium text-dark-700 dark:border-dark-700 dark:text-dark-200">{x}</span>)}</div></div>}{project.demoUrl&&<a href={project.demoUrl} target={/^https?:\/\//i.test(project.demoUrl)?'_blank':undefined} rel="noopener noreferrer" className="btn-secondary w-full justify-center">Open live demo <HiExternalLink/></a>}</div></aside></section>
 <AnimatePresence>{active!==null&&images[active]&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setActive(null)} className="fixed inset-0 z-[100] grid place-items-center bg-black/90 p-4"><button aria-label="Close gallery" onClick={()=>setActive(null)} className="absolute right-5 top-5 grid h-11 w-11 place-items-center rounded-full bg-white/10 text-white"><HiX size={24}/></button><div onClick={e=>e.stopPropagation()} className="relative flex max-h-[88vh] w-full max-w-6xl items-center justify-center"><img src={images[active]} alt={`${project.title} full screen`} className="max-h-[88vh] max-w-full object-contain"/>{images.length>1&&<><button aria-label="Previous image" onClick={()=>move(-1)} className="absolute left-2 grid h-12 w-12 place-items-center rounded-full bg-black/60 text-white sm:left-5"><HiChevronLeft size={28}/></button><button aria-label="Next image" onClick={()=>move(1)} className="absolute right-2 grid h-12 w-12 place-items-center rounded-full bg-black/60 text-white sm:right-5"><HiChevronRight size={28}/></button></>}</div><div className="absolute bottom-5 text-sm font-semibold text-white">{active+1} / {images.length}</div></motion.div>}</AnimatePresence>
 </main>}
function Fact({label,value}){return <div className="flex justify-between gap-4 py-4"><dt className="text-dark-400">{label}</dt><dd className="text-right font-semibold text-dark-800 dark:text-white">{value}</dd></div>}
