import {useEffect} from 'react';
import {useLocation} from 'react-router-dom';

export const SITE_URL=(import.meta.env.VITE_SITE_URL||'http://localhost:4173').replace(/\/$/,'');
const defaultImage='/images/infoaxon-logo.png';
const upsert=(selector,tag,attrs)=>{let node=document.head.querySelector(selector);if(!node){node=document.createElement(tag);document.head.appendChild(node)}Object.entries(attrs).forEach(([k,v])=>node.setAttribute(k,v));return node};

export default function SEO({title,description,path,robots='index, follow',image=defaultImage,type='website',jsonLd=[]}){const location=useLocation();useEffect(()=>{const cleanPath=(path||location.pathname).replace(/\/+$/,'')||'/';const canonical=SITE_URL+cleanPath;const absoluteImage=image?.startsWith('http')?image:SITE_URL+(image||defaultImage);document.title=title;upsert('meta[name="description"]','meta',{name:'description',content:description});upsert('meta[name="robots"]','meta',{name:'robots',content:robots});upsert('link[rel="canonical"]','link',{rel:'canonical',href:canonical});[['og:title',title],['og:description',description],['og:url',canonical],['og:type',type],['og:image',absoluteImage],['twitter:card','summary_large_image'],['twitter:title',title],['twitter:description',description],['twitter:image',absoluteImage]].forEach(([key,value])=>upsert(`meta[property="${key}"],meta[name="${key}"]`,'meta',key.startsWith('twitter')?{name:key,content:value}:{property:key,content:value}));if(import.meta.env.VITE_GOOGLE_SITE_VERIFICATION)upsert('meta[name="google-site-verification"]','meta',{name:'google-site-verification',content:import.meta.env.VITE_GOOGLE_SITE_VERIFICATION});document.querySelectorAll('script[data-seo-jsonld]').forEach(x=>x.remove());(Array.isArray(jsonLd)?jsonLd:[jsonLd]).filter(Boolean).forEach(data=>{const script=document.createElement('script');script.type='application/ld+json';script.dataset.seoJsonld='true';script.textContent=JSON.stringify(data).replace(/</g,'\\u003c');document.head.appendChild(script)});},[title,description,path,robots,image,type,jsonLd,location.pathname]);return null}

export const breadcrumbSchema=items=>({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:items.map((x,i)=>({'@type':'ListItem',position:i+1,name:x.name,item:SITE_URL+x.path}))});
