import {useEffect,useState} from 'react';
import {useParams} from 'react-router-dom';
import toast from 'react-hot-toast';
import {api,errorDetails} from '../lib/api';
import ResourceForm from './ResourceForm';
const labels={products:'Hardware Products',categories:'Product Categories',packages:'Software Packages',features:'Package Features',addons:'Package Add-ons',compatibility:'Compatibility Rules','erp-features':'ERP Key Features',solutions:'Website Solutions',projects:'Projects',inquiries:'Contact Inquiries',quotations:'Quotation Requests',settings:'Website Settings'};
const readOnly=['inquiries','quotations'];
const recordText=(r,i)=>r==='features'?[i.text,i.package?.name]:r==='addons'?[i.text,i.package?.name]:r==='compatibility'?[i.name,i.category?.name||i.product?.name]:[i.name||i.title||i.fullName||i.customerName||i.key,i.slug||i.email||i.category?.name];
export default function AdminResource(){
 const {resource}=useParams(),[items,setItems]=useState([]),[lookups,setLookups]=useState({}),[loading,setLoading]=useState(true),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState(''),[errors,setErrors]=useState({});
 const load=async()=>{setLoading(true);try{const [rows,refs]=await Promise.all([api.get('/admin/'+resource),readOnly.includes(resource)?Promise.resolve({data:{}}):api.get('/admin/lookups')]);setItems(rows.data);setLookups(refs.data)}catch(e){toast.error(errorDetails(e).summary)}finally{setLoading(false)}};
 useEffect(()=>{load()},[resource]);
 const save=async body=>{setSaving(true);setErrors({});try{const id=editing?.id;await api({url:'/admin/'+resource+(id?'/'+id:''),method:id?'put':'post',data:body});toast.success(id?'Changes saved':'Record created');setEditing(null);await load()}catch(e){const d=errorDetails(e);setErrors(d.fields);toast.error(d.summary)}finally{setSaving(false)}};
 const remove=async item=>{const [title]=recordText(resource,item);if(!confirm('Delete “'+title+'”? This cannot be undone.'))return;setDeleting(item.id);try{await api.delete('/admin/'+resource+'/'+item.id);toast.success('Record deleted');await load()}catch(e){const d=errorDetails(e);if(e.response?.data?.requiresCascade&&confirm(d.summary+'\n\nConfirm cascade behavior?')){try{await api.delete('/admin/'+resource+'/'+item.id+'?cascade=true');toast.success('Record deleted');await load()}catch(inner){toast.error(errorDetails(inner).summary)}}else toast.error(d.summary)}finally{setDeleting('')}};
 return <div className="min-w-0 space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-white">{labels[resource]||resource}</h1><p className="text-sm text-dark-400">{items.length} records</p></div>{!readOnly.includes(resource)&&<button onClick={()=>{setErrors({});setEditing({})}} className="admin-btn-primary">Add record</button>}</div>{loading?<p className="text-dark-400">Loading…</p>:<><div className="hidden overflow-hidden rounded-xl border border-dark-800 md:block"><table className="w-full table-fixed text-left text-sm"><thead className="bg-dark-900 text-dark-300"><tr><th className="w-1/2 p-4">Record</th><th className="p-4">Status / order</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{items.map(item=>{const [a,b]=recordText(resource,item);return <tr key={item.id} className="border-t border-dark-800 text-dark-300"><td className="p-4"><b className="block truncate text-white">{a}</b><span className="text-xs text-dark-500">{b}</span></td><td className="p-4">{resource==='features'?(item.featured?'Featured':'Full feature'):(item.status||item.stockStatus||(item.enabled===false?'Disabled':'Active'))} · {item.displayOrder??'—'}</td><td className="p-4 text-right">{!readOnly.includes(resource)&&<><button onClick={()=>{setErrors({});setEditing(item)}} className="mr-3 text-primary-400">Edit</button><button disabled={deleting===item.id} onClick={()=>remove(item)} className="text-red-400 disabled:opacity-50">{deleting===item.id?'Deleting…':'Delete'}</button></>}</td></tr>})}</tbody></table></div><div className="space-y-3 md:hidden">{items.map(item=>{const [a,b]=recordText(resource,item);return <article key={item.id} className="admin-card p-4"><b className="text-white">{a}</b><p className="text-sm text-dark-500">{b}</p><p className="my-3 text-sm text-dark-300">{item.status||item.stockStatus||(item.enabled===false?'Disabled':'Active')}</p>{!readOnly.includes(resource)&&<div className="flex gap-4"><button onClick={()=>setEditing(item)} className="text-primary-400">Edit</button><button onClick={()=>remove(item)} className="text-red-400">Delete</button></div>}</article>})}</div>{!items.length&&<p className="p-8 text-center text-dark-500">No records found.</p>}</>}{editing&&<div className="fixed inset-0 z-[80] overflow-y-auto bg-black/75 p-3 sm:p-6"><div className="mx-auto my-3 w-full max-w-4xl rounded-2xl border border-dark-700 bg-dark-900 p-4 sm:p-6"><h2 className="mb-5 text-xl font-bold text-white">{editing.id?'Edit':'Add'} {labels[resource]}</h2><ResourceForm resource={resource} item={editing} lookups={lookups} errors={errors} onSubmit={save} onCancel={()=>setEditing(null)} saving={saving}/></div></div>}</div>
}
