import {useEffect,useMemo,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {HiArrowLeft,HiTrash,HiUpload} from 'react-icons/hi';
import toast from 'react-hot-toast';
import {api,errorDetails} from '../lib/api';
const empty={title:'',description:'',badge:'',ctaText:'',ctaLink:'',enabled:true,startDate:'',endDate:'',displayOrder:0,imageUrl:'',fitMode:'contain',positionX:'center',positionY:'center',durationSeconds:6};
const localDate=v=>v?new Date(v).toISOString().slice(0,16):'';
export default function AdvertisementForm(){
 const {id}=useParams(),navigate=useNavigate();const [form,setForm]=useState(empty),[file,setFile]=useState(null),[removed,setRemoved]=useState(false),[saving,setSaving]=useState(false),[loading,setLoading]=useState(Boolean(id)),[errors,setErrors]=useState({});const preview=useMemo(()=>file?URL.createObjectURL(file):(removed?'':form.imageUrl),[file,removed,form.imageUrl]);
 useEffect(()=>()=>{if(file&&preview.startsWith('blob:'))URL.revokeObjectURL(preview)},[file,preview]);useEffect(()=>{if(!id)return;api.get('/admin/advertisements/'+id).then(r=>setForm({...empty,...r.data,startDate:localDate(r.data.startDate),endDate:localDate(r.data.endDate)})).catch(e=>{toast.error(errorDetails(e).summary);navigate('/admin/advertisements')}).finally(()=>setLoading(false))},[id,navigate]);const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 const choose=e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type))return toast.error('Choose a PNG, JPG, JPEG, or WebP image');setFile(f);setRemoved(false)};const remove=()=>{if(confirm('Remove this image? The advertisement will not appear publicly without an image.')){setFile(null);setRemoved(true)}};
 const submit=async e=>{e.preventDefault();setSaving(true);setErrors({});try{if(!id&&!file)throw Object.assign(new Error('Advertisement image is required'),{localImage:true});const data=new FormData();Object.entries(form).filter(([k])=>k!=='imageUrl').forEach(([k,v])=>data.append(k,['startDate','endDate'].includes(k)?(v?new Date(v).toISOString():''):String(v??'')));data.append('removeImage',String(removed));if(file)data.append('image',file);await api({url:'/admin/advertisements'+(id?'/'+id:''),method:id?'put':'post',data,headers:{'Content-Type':'multipart/form-data'}});toast.success(id?'Advertisement updated':'Advertisement created');navigate('/admin/advertisements')}catch(e){const d=errorDetails(e);setErrors(e.localImage?{image:['Select an advertisement image']}:d.fields);toast.error(e.localImage?e.message:d.summary)}finally{setSaving(false)}};
 if(loading)return <div className="admin-card text-dark-300">Loading advertisement...</div>;const numberInput=(name,label,min,max,help)=><label className="text-sm text-dark-200">{label}<input className="admin-input mt-2" type="number" min={min} max={max} value={form[name]} onChange={e=>set(name,Number(e.target.value))}/>{help&&<span className="mt-1 block text-xs text-dark-500">{help}</span>}{errors?.[name]?.map(x=><span key={x} className="mt-1 block text-xs text-red-400">{x}</span>)}</label>;const input=(name,label,type='text')=>name==='displayOrder'?<>{numberInput('displayOrder','Display order',0,100000)}{numberInput('durationSeconds','Slide duration (seconds)',2,60,'How long this advertisement stays visible before the next slide.')}</>:<label className="text-sm text-dark-200">{label}<input className="admin-input mt-2" type={type} value={form[name]||''} onChange={e=>set(name,e.target.value)}/>{errors?.[name]?.map(x=><span key={x} className="mt-1 block text-xs text-red-400">{x}</span>)}</label>;const select=(name,label,values)=><label className="text-sm text-dark-200">{label}<select className="admin-input mt-2" value={form[name]} onChange={e=>set(name,e.target.value)}>{values.map(v=><option key={v} value={v}>{v[0].toUpperCase()+v.slice(1)}</option>)}</select></label>;
 return <div className="mx-auto max-w-5xl space-y-5"><header className="flex items-center gap-4"><Link to="/admin/advertisements" className="admin-btn-secondary p-3"><HiArrowLeft/></Link><div><h1 className="text-2xl font-bold text-white">{id?'Edit Advertisement':'Add Advertisement'}</h1><p className="text-sm text-dark-400">Preview uses the same aspect ratio and fitting as the homepage carousel.</p></div></header><form onSubmit={submit} className="space-y-5"><section className="admin-card grid gap-5 lg:grid-cols-2"><div>{preview?<div className="aspect-[16/10] overflow-hidden rounded-xl bg-slate-200 dark:bg-slate-900"><img src={preview} alt="Preview" className={`h-full w-full ${form.fitMode==='cover'?'object-cover':'object-contain'}`} style={{objectPosition:`${form.positionX} ${form.positionY}`}}/></div>:<div className="grid aspect-[16/10] place-items-center rounded-xl bg-slate-900 text-dark-500">No image selected</div>}{errors?.image?.map(x=><p key={x} className="mt-1 text-xs text-red-400">{x}</p>)}</div><div className="flex flex-col justify-center gap-3"><label className="admin-btn-secondary flex cursor-pointer justify-center gap-2"><HiUpload/>{preview?'Replace Image':'Upload Image'}<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={choose}/></label>{preview&&<button type="button" onClick={remove} className="admin-btn-danger flex justify-center gap-2"><HiTrash/>Remove Image</button>}<p className="text-xs text-dark-500">The original image is preserved; display settings do not permanently crop it.</p></div></section><section className="admin-card grid gap-5 sm:grid-cols-2">{select('fitMode','Fit mode',['contain','cover'])}{select('positionX','Horizontal position',['left','center','right'])}{select('positionY','Vertical position',['top','center','bottom'])}{input('title','Title (optional)')}{input('badge','Badge text')}{input('ctaText','CTA text')}{input('ctaLink','CTA link')}{input('startDate','Start date','datetime-local')}{input('endDate','End date','datetime-local')}{input('displayOrder','Display order','number')}<label className="flex min-h-12 items-center gap-3 rounded-lg border border-dark-700 bg-dark-900 px-4 text-dark-200"><input type="checkbox" checked={form.enabled} onChange={e=>set('enabled',e.target.checked)}/>Enabled</label><label className="sm:col-span-2 text-sm text-dark-200">Short description<textarea className="admin-textarea mt-2" rows="4" value={form.description||''} onChange={e=>set('description',e.target.value)}/></label></section><div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Link to="/admin/advertisements" className="admin-btn-secondary text-center">Cancel</Link><button disabled={saving} className="admin-btn-primary">{saving?'Saving...':'Save Advertisement'}</button></div></form></div>;
}
