import {useEffect,useState} from 'react';
import toast from 'react-hot-toast';
import {api,errorDetails} from '../lib/api';
const resources=[['solutions','Solutions'],['projects','Projects'],['products','Hardware Products'],['advertisements','Advertisements']];
const empty={seoTitle:'',seoDescription:'',canonicalPath:'',ogImage:'',indexable:true};
export default function ManageSEO(){
 const [resource,setResource]=useState('solutions'),[items,setItems]=useState([]),[selected,setSelected]=useState(''),[form,setForm]=useState(empty),[saving,setSaving]=useState(false);
 useEffect(()=>{api.get('/admin/seo/'+resource).then(r=>{setItems(r.data);setSelected('');setForm(empty)}).catch(e=>toast.error(errorDetails(e).summary))},[resource]);
 const choose=id=>{setSelected(id);setForm({...empty,...items.find(v=>v.id===id)})};
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 const save=async e=>{e.preventDefault();setSaving(true);try{await api.patch(`/admin/seo/${resource}/${selected}`,{seoTitle:form.seoTitle||null,seoDescription:form.seoDescription||null,canonicalPath:form.canonicalPath||null,ogImage:form.ogImage||null,indexable:form.indexable});toast.success('SEO settings saved')}catch(e){toast.error(errorDetails(e).summary)}finally{setSaving(false)}};
 return <div className="mx-auto max-w-4xl space-y-6"><header><h1 className="text-3xl font-bold text-white">SEO Management</h1><p className="text-dark-400">Search metadata for dynamic public content.</p></header><section className="admin-card grid gap-4 sm:grid-cols-2"><Select label="Content type" value={resource} onChange={e=>setResource(e.target.value)} options={resources}/><Select label="Record" value={selected} onChange={e=>choose(e.target.value)} options={items.map(x=>[x.id,x.title||x.name||'Untitled'])}/></section>{selected&&<form onSubmit={save} className="admin-card space-y-5"><Field label="SEO title" value={form.seoTitle||''} maxLength={70} guide="Recommended 50-60" onChange={e=>set('seoTitle',e.target.value)}/><label className="block text-sm text-dark-300">Meta description<textarea className="admin-textarea mt-2" maxLength={200} rows="4" value={form.seoDescription||''} onChange={e=>set('seoDescription',e.target.value)}/><Guide value={form.seoDescription} text="Recommended 140-160"/></label><Field label="Canonical path" placeholder="/solutions/example" value={form.canonicalPath||''} onChange={e=>set('canonicalPath',e.target.value)}/><Field label="Open Graph image" value={form.ogImage||''} onChange={e=>set('ogImage',e.target.value)}/>{form.ogImage&&<img src={form.ogImage} alt="Social sharing preview" className="aspect-[1.91/1] max-w-lg rounded-xl object-cover"/>}<label className="flex items-center gap-3 text-dark-200"><input type="checkbox" checked={form.indexable} onChange={e=>set('indexable',e.target.checked)}/>Indexable</label><button disabled={saving} className="admin-btn-primary">{saving?'Saving...':'Save SEO Settings'}</button></form>}</div>;
}
function Select({label,options,...p}){return <label className="text-sm text-dark-300">{label}<select className="admin-input mt-2" {...p}><option value="">Select...</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Field({label,guide,...p}){return <label className="block text-sm text-dark-300">{label}<input className="admin-input mt-2" {...p}/>{guide&&<Guide value={p.value} text={guide}/>}</label>}
function Guide({value,text}){return <span className="mt-1 flex justify-between text-xs text-dark-500"><span>{text}</span><span>{(value||'').length} characters</span></span>}
