import {useEffect,useMemo,useState} from 'react';

const defaults={
  products:{name:'',slug:'',categoryId:'',shortDescription:'',fullDescription:'',specifications:{},price:0,warranty:'',stockQuantity:0,stockStatus:'IN_STOCK',imageUrl:'',featured:false,enabled:true,displayOrder:0},
  categories:{name:'',slug:'',enabled:true,displayOrder:0},
  packages:{name:'',slug:'',startingPrice:0,suitableFor:'',summary:'',supportPeriod:'',licenceNote:'',mostPopular:false,enabled:true,displayOrder:0,features:[],addons:[]},
  features:{packageId:'',text:'',featured:false,enabled:true,displayOrder:0},addons:{packageId:'',text:'',displayOrder:0},
  compatibility:{name:'',categoryId:'',productId:'',level:'REQUIRED',message:'',explanation:'',suggestedProductId:'',allowOwnedConfirmation:false,enabled:true,displayOrder:0},
  'erp-features':{number:'',title:'',description:'',imageUrl:'',enabled:true,displayOrder:0},
  solutions:{slug:'',title:'',subtitle:'',description:'',icon:'',imageUrl:'',content:{},enabled:true,displayOrder:0},
  projects:{slug:'',title:'',category:'',description:'',imageUrl:'',content:{},featured:false,enabled:true,displayOrder:0},
  settings:{key:'',value:'',type:'text',enabled:true,description:''}
};
const definitions={
  products:[['name','Product name','text',true],['slug','Slug','text',true],['categoryId','Product category','categories',true],['shortDescription','Short description','textarea',true],['fullDescription','Full description','textarea'],['price','Price','number',true],['warranty','Warranty','text'],['stockQuantity','Stock quantity','number',true],['stockStatus','Stock status',['IN_STOCK','LOW_STOCK','OUT_OF_STOCK','TO_ORDER'],true],['imageUrl','Image URL','image'],['featured','Featured','checkbox'],['enabled','Enabled','checkbox'],['displayOrder','Display order','number']],
  categories:[['name','Category name','text',true],['slug','Slug','text',true],['enabled','Enabled','checkbox'],['displayOrder','Display order','number']],
  features:[['text','Feature text','text',true],['packageId','Software package','packages',true],['featured','Main / featured','checkbox'],['enabled','Enabled','checkbox'],['displayOrder','Display order','number']],
  addons:[['text','Add-on text','text',true],['packageId','Software package','packages',true],['displayOrder','Display order','number']],
  compatibility:[['name','Rule name','text',true],['categoryId','Product category','categories'],['productId','Specific product','products'],['level','Requirement level',['REQUIRED','RECOMMENDED'],true],['message','Customer message','textarea',true],['explanation','Explanation','textarea',true],['suggestedProductId','Suggested product','products'],['allowOwnedConfirmation','Allow customer-owned confirmation','checkbox'],['enabled','Enabled','checkbox'],['displayOrder','Display order','number']],
  'erp-features':[['number','Feature number','text',true],['title','Title','text',true],['description','Description','textarea',true],['imageUrl','Image URL','image'],['enabled','Enabled','checkbox'],['displayOrder','Display order','number']],
  solutions:[['title','Solution title','text',true],['slug','Slug','text',true],['subtitle','Subtitle','text'],['description','Description','textarea',true],['icon','Icon name','text'],['imageUrl','Image URL','image'],['enabled','Enabled','checkbox'],['displayOrder','Display order','number']],
  projects:[['title','Project title','text',true],['slug','Slug','text',true],['category','Project category','text'],['description','Description','textarea',true],['imageUrl','Image URL','image'],['featured','Featured','checkbox'],['enabled','Enabled','checkbox'],['displayOrder','Display order','number']],
  settings:[['key','Setting key','text',true],['type','Type',['text','number','boolean','JSON'],true],['value','Setting value','setting',true],['description','Description','textarea'],['enabled','Enabled','checkbox']]
};
const slugify=v=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const Label=({children,required})=><label className="mb-2 block text-sm font-medium text-dark-300">{children}{required&&<span className="text-red-400"> *</span>}</label>;

function KeyValueRows({value,onChange,label='Specifications'}){
  const rows=Object.entries(value||{});
  const set=(i,part,v)=>{const next=rows.map((r,n)=>n===i?(part===0?[v,r[1]]:[r[0],v]):r);onChange(Object.fromEntries(next.filter(([k])=>k)))};
  return <div className="sm:col-span-2"><Label>{label}</Label><div className="space-y-2">{rows.map(([k,v],i)=><div key={i} className="grid grid-cols-[1fr_1fr_auto] gap-2"><input className="admin-input" value={k} placeholder="Name" onChange={e=>set(i,0,e.target.value)}/><input className="admin-input" value={String(v??'')} placeholder="Value" onChange={e=>set(i,1,e.target.value)}/><button type="button" className="admin-btn-danger px-3" onClick={()=>onChange(Object.fromEntries(rows.filter((_,n)=>n!==i)))}>Remove</button></div>)}</div><button type="button" className="admin-btn-secondary mt-2" onClick={()=>onChange({...value,['field_'+(rows.length+1)]:''})}>Add row</button></div>
}
function RepeatRows({title,rows,onChange,featured=false}){
  const add=()=>onChange([...rows,{text:'',featured:false,displayOrder:rows.length}]);
  const change=(i,k,v)=>onChange(rows.map((r,n)=>n===i?{...r,[k]:v}:r));
  return <section className="sm:col-span-2 rounded-xl border border-dark-700 p-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold text-white">{title}</h3><button type="button" onClick={add} className="admin-btn-secondary px-3 py-2">Add row</button></div><div className="space-y-3">{rows.map((row,i)=><div key={i} className="grid gap-2 rounded-lg bg-dark-900/60 p-3 sm:grid-cols-[1fr_8rem_auto_auto]"><input className="admin-input" value={row.text} placeholder="Feature text" onChange={e=>change(i,'text',e.target.value)}/><input className="admin-input" type="number" min="0" value={row.displayOrder} aria-label="Display order" onChange={e=>change(i,'displayOrder',Number(e.target.value))}/>{featured&&<label className="flex items-center gap-2 text-sm text-dark-300"><input type="checkbox" checked={row.featured} onChange={e=>change(i,'featured',e.target.checked)}/> Featured</label>}<button type="button" className="text-sm text-red-400" onClick={()=>onChange(rows.filter((_,n)=>n!==i))}>Remove</button></div>)}</div>{!rows.length&&<p className="text-sm text-dark-500">No rows yet.</p>}</section>
}
export default function ResourceForm({resource,item,lookups,errors,onSubmit,onCancel,saving}){
  const [form,setForm]=useState(()=>({...defaults[resource],...item}));
  useEffect(()=>setForm({...defaults[resource],...item}),[item,resource]);
  const fields=useMemo(()=>resource==='packages'?[['name','Package name','text',true],['slug','Slug','text',true],['startingPrice','Starting price','number',true],['suitableFor','Suitable for','text',true],['summary','Summary','textarea',true],['supportPeriod','Support period','text',true],['licenceNote','Licence note','textarea'],['mostPopular','Most Popular','checkbox'],['enabled','Enabled','checkbox'],['displayOrder','Display order','number']]:definitions[resource]||[],[resource]);
  const update=(name,value)=>setForm(f=>({...f,[name]:value,...(name==='name'&&!item?.id&&f.slug===''?{slug:slugify(value)}:{})}));
  const submit=e=>{e.preventDefault();let payload={...form};if(resource==='settings'){try{payload.value=form.type==='number'?Number(form.value):form.type==='boolean'?(form.value===true||form.value==='true'):form.type==='JSON'?JSON.parse(form.value):String(form.value)}catch{ return }}onSubmit(payload)};
  return <form onSubmit={submit} className="space-y-5"><div className="grid gap-5 sm:grid-cols-2">{fields.map(([name,label,type,required])=><div key={name} className={(type==='textarea'||type==='image'||type==='setting')?'sm:col-span-2':''}>{type!=='checkbox'&&<Label required={required}>{label}</Label>}{type==='checkbox'?<label className="flex min-h-12 items-center gap-3 rounded-lg border border-dark-700 bg-dark-900 px-4 text-dark-300"><input type="checkbox" checked={Boolean(form[name])} onChange={e=>update(name,e.target.checked)}/>{label}</label>:Array.isArray(type)?<select className="admin-input" value={form[name]??''} required={required} onChange={e=>update(name,e.target.value)}>{type.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select>:['categories','products','packages'].includes(type)?<select className="admin-input" value={form[name]??''} required={required} onChange={e=>update(name,e.target.value)}><option value="">Select…</option>{(lookups[type]||[]).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select>:type==='textarea'?<textarea className="admin-textarea" rows="4" value={form[name]??''} required={required} onChange={e=>update(name,e.target.value)}/>:type==='setting'?(form.type==='boolean'?<select className="admin-input" value={String(form[name])} onChange={e=>update(name,e.target.value)}><option value="true">true</option><option value="false">false</option></select>:<textarea className="admin-textarea" rows={form.type==='JSON'?6:2} value={typeof form[name]==='object'?JSON.stringify(form[name],null,2):form[name]??''} required onChange={e=>update(name,e.target.value)}/>):<><input className="admin-input" type={type==='image'?'url':type} min={type==='number'?0:undefined} value={form[name]??''} required={required} onChange={e=>update(name,type==='number'?Number(e.target.value):e.target.value)}/>{type==='image'&&form[name]&&<img src={form[name]} alt="" className="mt-3 h-32 max-w-full rounded-lg object-cover" onError={e=>e.currentTarget.classList.add('hidden')}/>}</>}{errors?.[name]?.map(m=><p key={m} className="mt-1 text-xs text-red-400">{m}</p>)}</div>)}{resource==='products'&&<KeyValueRows value={form.specifications} onChange={v=>update('specifications',v)}/>} {['solutions','projects'].includes(resource)&&<KeyValueRows label="Additional content fields" value={form.content} onChange={v=>update('content',v)}/>} {resource==='packages'&&<><RepeatRows title="Main and full features" rows={form.features||[]} onChange={v=>update('features',v)} featured/><RepeatRows title="Optional add-ons" rows={form.addons||[]} onChange={v=>update('addons',v)}/></>}</div><div className="flex flex-col-reverse gap-3 border-t border-dark-700 pt-4 sm:flex-row sm:justify-end"><button type="button" onClick={onCancel} disabled={saving} className="admin-btn-secondary">Cancel</button><button disabled={saving} className="admin-btn-primary disabled:cursor-wait disabled:opacity-60">{saving?'Saving…':'Save changes'}</button></div></form>
}
