import {createContext,useCallback,useContext,useEffect,useState} from 'react';
import {api,messageOf} from '../lib/api';
import {defaultCompanyInfo} from '../data/defaultData';
const DataContext=createContext();
export function DataProvider({children}){
  const [state,setState]=useState({solutions:[],projects:[],companyInfo:defaultCompanyInfo,loading:true,error:''});
  const refresh=useCallback(async()=>{setState(s=>({...s,loading:true,error:''}));try{const [solutions,projects,company]=await Promise.all([api.get('/solutions'),api.get('/projects'),api.get('/company')]);const row=company.data||{};const normalizedSolutions=solutions.data.map(s=>{const base={...(s.content||{}),...s,id:s.slug,databaseId:s.id};const plans=(s.packages||[]).map(p=>({id:p.slug,name:p.name,price:Number(p.startingPrice).toLocaleString('en-US'),description:p.summary,suitableFor:p.suitableFor,supportPeriod:p.supportPeriod,note:p.licenceNote,badge:p.mostPopular?'Most Popular':null,features:p.features.map(f=>f.text),keyFeatures:p.features.filter(f=>f.featured).map(f=>f.text),optionalAddOns:p.addons.map(a=>a.text),cta:'Choose '+p.name,ctaStyle:p.mostPopular?'btn-primary':'btn-secondary'}));return{...base,features:(s.keyFeatures||[]).map(f=>f.title),pricing:plans.length?{id:s.slug,title:s.title,tagline:s.description,color:base.color||'from-primary-500 to-cyan-500',colorBorder:'border-primary-500/30',plans}:null}});setState({solutions:normalizedSolutions,projects:projects.data.map(p=>({...p.content,...p,id:p.slug,databaseId:p.id})),companyInfo:{...defaultCompanyInfo,...(row.content||{}),...row,socialLinks:row.socialLinks||row.content?.socialLinks||defaultCompanyInfo.socialLinks},loading:false,error:''});}catch(error){setState(s=>({...s,loading:false,error:messageOf(error)}));}},[]);
  useEffect(()=>{refresh();},[refresh]);
  const solutionPayload=v=>({slug:v.id,title:v.title,subtitle:v.subtitle||v.tagline||null,description:v.description||v.title,icon:typeof v.icon==='string'?v.icon:null,imageUrl:v.image||v.imageUrl||null,content:v});
  const projectPayload=v=>({slug:v.id,title:v.title,category:v.category||null,description:v.description||v.title,imageUrl:v.image||v.imageUrl||null,featured:Boolean(v.featured),content:v});
  const companyPayload=v=>{const {name,phone,email,address,whatsapp,socialLinks,footerDetails,...content}=v;return{name:name||'InfoAxon Software Solutions',phone:phone||null,email:email||null,address:address||null,whatsapp:whatsapp||null,socialLinks:socialLinks||{},footerDetails:footerDetails||null,content}};
  const mutate=async(resource,method,id,data)=>{const response=await api({url:`/admin/${resource}${id?`/${id}`:''}`,method,data});await refresh();return response.data;};
  return <DataContext.Provider value={{...state,refresh,addSolution:(v)=>mutate('solutions','post',null,solutionPayload(v)),updateSolution:(id,v)=>mutate('solutions','put',state.solutions.find(x=>x.id===id)?.databaseId||id,solutionPayload(v)),deleteSolution:(id)=>mutate('solutions','delete',state.solutions.find(x=>x.id===id)?.databaseId||id),addProject:(v)=>mutate('projects','post',null,projectPayload(v)),updateProject:(id,v)=>mutate('projects','put',state.projects.find(x=>x.id===id)?.databaseId||id,projectPayload(v)),deleteProject:(id)=>mutate('projects','delete',state.projects.find(x=>x.id===id)?.databaseId||id),updateCompanyInfo:(v)=>mutate('company','put',null,companyPayload(v))}}>{children}</DataContext.Provider>;
}
export function useData(){const value=useContext(DataContext);if(!value)throw new Error('useData must be used within DataProvider');return value;}
