DELETE FROM "PackageFeature" WHERE "packageId" IN (SELECT id FROM "SoftwarePackage" WHERE slug IN ('erp-starter','erp-professional','erp-enterprise'));

INSERT INTO "PackageFeature" ("id","packageId","text","featured","enabled","displayOrder")
SELECT 'full-'||p.slug||'-'||v.ord,p.id,v.text,v.ord<=7,true,v.ord
FROM "SoftwarePackage" p
JOIN (VALUES
 ('erp-starter',1,'POS billing and checkout'),('erp-starter',2,'Product and category management'),('erp-starter',3,'Barcode scanning'),('erp-starter',4,'Receipt printing'),('erp-starter',5,'Customer management'),('erp-starter',6,'Basic stock tracking'),('erp-starter',7,'Daily and monthly sales reports'),('erp-starter',8,'Cash and card payment recording'),('erp-starter',9,'Discounts, returns and refunds'),('erp-starter',10,'Automatic stock reduction after sales'),('erp-starter',11,'Manual stock adjustments'),('erp-starter',12,'Stock-in and stock-out records'),('erp-starter',13,'Low-stock configuration'),('erp-starter',14,'POS session and basic stock reports'),('erp-starter',15,'Cashier and administrator login'),('erp-starter',16,'One branch and one POS counter'),('erp-starter',17,'Standard receipt setup'),('erp-starter',18,'Excel import up to 500 products'),('erp-starter',19,'Remote installation'),('erp-starter',20,'One staff training session'),('erp-starter',21,'30 days free corrective support'),
 ('erp-professional',1,'Everything in Starter'),('erp-professional',2,'Supplier and purchase management'),('erp-professional',3,'Expense and outstanding tracking'),('erp-professional',4,'Product costing and stock valuation'),('erp-professional',5,'Advanced sales and profit reports'),('erp-professional',6,'Multiple users and roles'),('erp-professional',7,'Custom receipt and selected reports'),('erp-professional',8,'Purchase orders and goods receiving'),('erp-professional',9,'Purchase history and vendor price tracking'),('erp-professional',10,'FIFO, AVCO and Standard Cost configuration'),('erp-professional',11,'Stock valuation and movement history'),('erp-professional',12,'Inventory adjustments and purchase returns'),('erp-professional',13,'Damaged stock and scrap handling'),('erp-professional',14,'Customer credit and outstanding tracking'),('erp-professional',15,'Expense recording and categories'),('erp-professional',16,'Product and category sales reports'),('erp-professional',17,'Product-wise profit reports'),('erp-professional',18,'Cashier-wise reports'),('erp-professional',19,'Larger product import'),('erp-professional',20,'Extended staff training'),('erp-professional',21,'3 months free corrective support'),
 ('erp-enterprise',1,'Everything in Professional'),('erp-enterprise',2,'Multiple branches and warehouses'),('erp-enterprise',3,'Branch stock transfers'),('erp-enterprise',4,'Batch, serial and expiry tracking'),('erp-enterprise',5,'Advanced accounting and approvals'),('erp-enterprise',6,'Custom dashboards and workflows'),('erp-enterprise',7,'API and third-party integrations'),('erp-enterprise',8,'Multiple stock locations'),('erp-enterprise',9,'Branch-wise sales, stock and profit reports'),('erp-enterprise',10,'Consolidated dashboard'),('erp-enterprise',11,'Expiration alerts'),('erp-enterprise',12,'Advanced stock traceability and valuation'),('erp-enterprise',13,'Vendor bills and customer invoices'),('erp-enterprise',14,'Payment and outstanding management'),('erp-enterprise',15,'Pricelists, promotions and loyalty'),('erp-enterprise',16,'Advanced permissions'),('erp-enterprise',17,'Custom reports and dashboards'),('erp-enterprise',18,'Odoo Studio customization'),('erp-enterprise',19,'Payment gateway, WhatsApp and SMS options'),('erp-enterprise',20,'Advanced data migration'),('erp-enterprise',21,'Requirement-based staff training'),('erp-enterprise',22,'3 months priority corrective support')
) v(slug,ord,text) ON v.slug=p.slug;

INSERT INTO "PackageAddon" ("id","packageId","text","displayOrder")
SELECT 'erp-pro-addon-'||v.ord,p.id,v.text,v.ord
FROM "SoftwarePackage" p
JOIN (VALUES (1,'Batch and expiry tracking'),(2,'Additional counters or branches'),(3,'Loyalty programme'),(4,'Customer-specific pricelists'),(5,'WhatsApp or SMS notifications'),(6,'Advanced dashboard'),(7,'Custom reports'),(8,'Accounting integration')) v(ord,text) ON true
WHERE p.slug='erp-professional'
AND NOT EXISTS (SELECT 1 FROM "PackageAddon" a WHERE a."packageId"=p.id);
